// ============================================================
// PEDIATRIC PHYSICAL EXAMINATION CLUES
// ============================================================

const PEDS_PE_CLUES = {
    // General & Vitals
    "Pallor": "Think anaemia, chronic disease, or blood loss.",
    "Jaundiced": "Consider hepatitis, obstruction, or haemolysis.",
    "Cyanosed": "Hypoxaemia or poor perfusion. Check SpO₂, respiratory effort, pulses.",
    "Oedematous": "Heart failure, renal disease, liver disease, or malnutrition.",
    "Dehydrated": "Reduced intake, losses (diarrhoea, vomiting), or third‑space losses.",
    "Malnourished": "Chronic undernutrition, infection, or malabsorption.",
    "Dysmorphic features": "Consider genetic or congenital syndromes.",
    "Lymphadenopathy present": "Infection, TB, HIV, lymphoma, or malignancy.",
    "Reduced skin turgor": "Dehydration – assess intake, losses, and urine output.",
    // Respiratory
    "Barrel chest": "Chronic hyperinflation – asthma, COPD, cystic fibrosis.",
    "Chest asymmetry": "Pneumothorax, effusion, or collapse.",
    "Harrison's sulcus": "Chronic respiratory distress, rickets.",
    "Chest indrawing (subcostal)": "Lower airway obstruction – pneumonia, bronchiolitis.",
    "Intercostal recession": "Increased work of breathing – asthma, bronchiolitis.",
    "Nasal flaring": "Respiratory distress – pneumonia, bronchiolitis.",
    "Tracheal tug": "Severe respiratory distress – croup, epiglottitis.",
    "Head nodding": "Severe respiratory distress – metabolic acidosis (e.g., DKA).",
    "Grunting": "Severe pneumonia, pulmonary oedema – urgent.",
    "Use of accessory muscles": "Respiratory distress – asthma, pneumonia, COPD.",
    "Trachea deviated": "Tension pneumothorax, large effusion, or mass.",
    "Reduced chest expansion": "Pleural effusion, fibrosis, or collapse.",
    "Tactile fremitus increased": "Consolidation – pneumonia, tumour.",
    "Tactile fremitus reduced": "Effusion, pneumothorax, or fibrosis.",
    "Dull": "Consolidation or effusion.",
    "Stony dull": "Pleural effusion – urgent drainage.",
    "Hyperresonant": "Pneumothorax or hyperinflation.",
    "Bronchial breathing": "Consolidation above a patent airway.",
    "Reduced air entry": "Effusion, collapse, or pneumothorax.",
    "Absent air entry": "Massive effusion or pneumothorax.",
    "Fine crackles": "Fibrosis, early oedema, interstitial disease.",
    "Coarse crackles": "Secretions, bronchiectasis, pulmonary oedema.",
    "Wheeze (expiratory)": "Asthma, bronchiolitis, lower airway narrowing.",
    "Stridor (inspiratory)": "Upper airway obstruction – croup, epiglottitis, foreign body.",
    "Pleural rub": "Pleurisy, pulmonary infarction.",
    // Cardiovascular
    "Precordial bulge": "Cardiomegaly – congenital heart disease, pericardial effusion.",
    "Scars (sternotomy)": "Previous cardiac surgery.",
    "Peripheral oedema": "Heart failure, renal disease, venous insufficiency.",
    "Clubbing": "Cyanotic heart disease, lung disease, IBD.",
    "Cyanosis (central)": "Hypoxaemia – congenital heart disease, pulmonary disease.",
    "Cyanosis (peripheral)": "Poor perfusion – shock, cold, or heart failure.",
    "Apex beat displaced": "Cardiomegaly – LV enlargement.",
    "Heave": "Ventricular hypertrophy – pressure overload.",
    "Thrill": "Palpable murmur – stenosis or shunt.",
    "Weak pulses": "Low cardiac output – shock, coarctation, severe AS.",
    "Bounding pulses": "High output state – PDA, aortic regurgitation, sepsis.",
    "Capillary refill >2s": "Shock, dehydration, or vasoconstriction.",
    "S3 (gallop)": "Heart failure or volume overload.",
    "S4": "Stiff ventricle – hypertension, aortic stenosis.",
    "Murmur present": "Valve lesion, shunt, or flow murmur – classify by timing, site, radiation.",
    "Pericardial rub": "Pericarditis – pain, fever, muffled sounds.",
    // Abdomen
    "Distended": "Gas, ascites, obstruction, or mass.",
    "Scaphoid": "Malnutrition or dehydration.",
    "Visible peristalsis": "Intestinal obstruction – urgent.",
    "Dilated veins": "Portal hypertension – liver disease.",
    "Umbilical hernia": "Common in African children; often resolves, but rule out obstruction.",
    "Surgical scars": "Previous surgery – inquire about indication.",
    "Striae": "Recent weight gain, Cushing's syndrome, or stretching.",
    "Bowel sounds absent": "Ileus or peritonitis – urgent.",
    "Bowel sounds increased (tinkling)": "Early obstruction – urgent.",
    "Bruit": "Vascular stenosis or aneurysm.",
    "Rigid/Guarding": "Peritonitis – surgical emergency.",
    "Tenderness (generalised)": "Diffuse peritoneal irritation.",
    "Tenderness (localised)": "Appendicitis, cholecystitis, abscess, etc.",
    "Hepatomegaly": "Heart failure, malaria, hepatitis, storage disease.",
    "Splenomegaly": "Malaria, portal hypertension, haematological disease.",
    "Hepatosplenomegaly": "Malaria, lymphoma, storage disease, HIV.",
    "Renal mass": "Wilms tumour, hydronephrosis, polycystic kidney.",
    "Other mass": "Tumour, abscess, or cyst – urgent imaging.",
    "Tympanic": "Normal gas pattern.",
    "Dull (solid organ)": "Enlarged liver, spleen, or mass.",
    "Dull (fluid — ascites)": "Ascites – liver, cardiac, renal, or malignant.",
    "Liver dullness normal": "Reassuring.",
    "Spleen dullness": "Splenomegaly.",
    "Shifting dullness": "Ascites – confirm with fluid thrill.",
    // Neurological
    "Drowsy": "Metabolic, CNS infection, raised ICP, or toxic.",
    "Confused": "Delirium, metabolic, encephalopathy.",
    "Unresponsive": "Coma – ABC, glucose, consider meningitis, malaria, trauma.",
    "Abnormal posture": "Decorticate (flexion) or decerebrate (extension) – raised ICP.",
    "Involuntary movements": "Seizures, chorea, dystonia – neurological condition.",
    "Bulging fontanelle": "Raised ICP – meningitis, hydrocephalus, mass.",
    "Sunken fontanelle": "Dehydration – urgent rehydration.",
    "Microcephaly": "Congenital infection, genetic, or prenatal insult.",
    "Macrocephaly": "Hydrocephalus, storage disease, genetic.",
    "Fontanelle tense": "Raised ICP – urgent assessment.",
    "Fontanelle flat": "Normal for age.",
    "Fontanelle sunken": "Dehydration.",
    "Neck stiffness": "Meningitis or SAH – urgent antibiotics and LP.",
    "Kernig's sign positive": "Meningeal irritation – meningitis.",
    "Brudzinski's sign positive": "Meningeal irritation – meningitis.",
    "Hypotonia": "LMN lesion, myopathy, or acute illness.",
    "Hypertonia": "UMN lesion – cerebral palsy, stroke, or metabolic.",
    "Weakness": "UMN or LMN lesion – localise.",
    "Hyperreflexia": "UMN lesion.",
    "Hyporeflexia": "LMN lesion.",
    "Babinski positive": "UMN lesion – corticospinal tract.",
    "Clonus": "UMN lesion – upper motor neuron.",
    "Pupils unequal": "CN III palsy, raised ICP, or local trauma.",
    "Facial asymmetry": "Facial nerve palsy, stroke, or congenital.",
    "Gaze deviation": "Brainstem lesion, stroke, or seizures.",
    // Skin
    "Rash (maculopapular)": "Measles, rubella, viral exanthem, drug reaction.",
    "Rash (vesicular)": "Chickenpox, herpes, hand‑foot‑mouth.",
    "Petechiae": "ITP, meningococcaemia, leukaemia – urgent if fever.",
    "Purpura": "Vasculitis, DIC, meningococcaemia – urgent.",
    "Bruising": "ITP, coagulation disorder, trauma, or non‑accidental injury.",
    "Flaky paint dermatosis": "Kwashiorkor – protein malnutrition.",
    "Wasting (loose skin)": "Marasmus – severe malnutrition.",
    "Oedema (pitting)": "Nephrotic, cardiac, or kwashiorkor.",
    "Oedema (non-pitting)": "Lymphoedema, myxoedema.",
    "Wounds/ulcers": "Infection, vascular insufficiency, or pressure.",
    "Scabies": "Intense itch, worse at night – treat whole family.",
    "Tinea": "Fungal infection – topical antifungals.",
    "Lymphadenopathy (cervical)": "Infection, TB, lymphoma.",
    "Lymphadenopathy (axillary)": "Infection, lymphoma, breast pathology.",
    "Lymphadenopathy (inguinal)": "Infection, lymphoma, lower limb malignancy.",
    "Generalised lymphadenopathy": "HIV, TB, lymphoma, leukaemia.",
    // ENT
    "Perforated TM": "AOM with perforation, trauma, or CSOM.",
    "Congested TM": "Acute otitis media – pain, fever.",
    "Ear discharge (purulent)": "Acute or chronic suppurative otitis media.",
    "Ear discharge (clear)": "CSF leak or allergy.",
    "Mastoid tenderness": "Mastoiditis – IV antibiotics.",
    "Inflamed throat": "Pharyngitis, tonsillitis – viral or bacterial.",
    "Tonsillar enlargement": "Infection, EBV, or obstruction.",
    "Tonsillar exudate": "Strep throat, tonsillitis.",
    "Oral thrush": "Candidiasis – HIV, immunosuppression, antibiotic use.",
    "Koplik's spots": "Measles – pathognomonic.",
    "Dry mucous membranes": "Dehydration – assess hydration status.",
    "Submandibular lymphadenopathy": "Oral or tonsillar infection.",
    "Parotid enlargement": "Mumps, parotitis, or tumour."
};